# Generated by Django 3.1 on 2020-08-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agile", "0002_alter_agile_principle_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="user name"),
                ),
                (
                    "email",
                    models.CharField(max_length=50, verbose_name="user email"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=30, verbose_name="user password"
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="date created"
                    ),
                ),
                (
                    "modified_date",
                    models.DateTimeField(
                        auto_now=True, verbose_name="date last modified"
                    ),
                ),
            ],
            options={"verbose_name_plural": "User"},
        ),
    ]
